#!/usr/bin/env python3
"""현재 실거래 선물 전략 설정 (2026-04-05 확정)."""

START = '2020-10-01'
END = '2026-03-28'

CURRENT_STRATEGIES = {
    "4h_d005": dict(
        interval="4h",
        sma_bars=240,
        mom_short_bars=20,
        mom_long_bars=720,
        canary_hyst=0.015,
        drift_threshold=0.0,
        dd_threshold=0,
        dd_lookback=0,
        bl_drop=0,
        bl_days=0,
        health_mode="mom2vol",
        vol_mode="daily",
        vol_threshold=0.05,
        n_snapshots=3,
        snap_interval_bars=60,
    ),
    "2h_S240": dict(
        interval="2h",
        sma_bars=240,
        mom_short_bars=20,
        mom_long_bars=720,
        canary_hyst=0.015,
        drift_threshold=0.0,
        dd_threshold=0,
        dd_lookback=0,
        bl_drop=0,
        bl_days=0,
        health_mode="mom2vol",
        vol_mode="bar",
        vol_threshold=0.60,
        n_snapshots=3,
        snap_interval_bars=120,
    ),
    "2h_S120": dict(
        interval="2h",
        sma_bars=120,
        mom_short_bars=20,
        mom_long_bars=720,
        canary_hyst=0.015,
        drift_threshold=0.0,
        dd_threshold=0,
        dd_lookback=0,
        bl_drop=0,
        bl_days=0,
        health_mode="mom2vol",
        vol_mode="bar",
        vol_threshold=0.60,
        n_snapshots=3,
        snap_interval_bars=120,
    ),
    "4h_M20": dict(
        interval="4h",
        sma_bars=240,
        mom_short_bars=20,
        mom_long_bars=120,
        canary_hyst=0.015,
        drift_threshold=0.0,
        dd_threshold=0,
        dd_lookback=0,
        bl_drop=0,
        bl_days=0,
        health_mode="mom2vol",
        vol_mode="bar",
        vol_threshold=0.60,
        n_snapshots=3,
        snap_interval_bars=21,
    ),
}

CURRENT_LIVE_COMBO = {k: 1 / 4 for k in CURRENT_STRATEGIES}
